/*
  # Create rainfall data table

  1. New Tables
    - `rainfallData`
      - `id` (bigint, primary key)
      - `created_at` (timestamp)
      - `rainfall` (double precision) - stores rainfall amount
      - `date` (date) - stores date in PostgreSQL date format

  2. Security
    - Enable RLS on `rainfallData` table
    - Add policy for public access (you can modify this based on your auth requirements)
*/

CREATE TABLE IF NOT EXISTS rainfallData (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  rainfall double precision NOT NULL DEFAULT 0,
  date date NOT NULL
);

-- Create unique constraint to prevent duplicate entries for the same date
ALTER TABLE rainfallData ADD CONSTRAINT rainfallData_date_unique UNIQUE (date);

-- Enable Row Level Security
ALTER TABLE rainfallData ENABLE ROW LEVEL SECURITY;

-- Create policy for public access (modify based on your authentication needs)
CREATE POLICY "Enable read access for all users"
  ON rainfallData
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Enable insert access for all users"
  ON rainfallData
  FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Enable update access for all users"
  ON rainfallData
  FOR UPDATE
  TO public
  USING (true);

CREATE POLICY "Enable delete access for all users"
  ON rainfallData
  FOR DELETE
  TO public
  USING (true);

-- Create index for better performance on date queries
CREATE INDEX IF NOT EXISTS rainfallData_date_idx ON rainfallData (date);
CREATE INDEX IF NOT EXISTS rainfallData_created_at_idx ON rainfallData (created_at);