/*
  # Create debt management tables

  1. New Tables
    - `debtData`
      - `id` (bigint, primary key)
      - `month_year` (text, required)
      - `worker_name` (text, required)
      - `category` (text, required)
      - `amount` (numeric, required, >= 0)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)
    - `debtOption`
      - `id` (bigint, primary key)
      - `category_name` (text, unique, required)
      - `description` (text, optional)
      - `created_at` (timestamp)

  2. Security
    - Enable RLS on both tables
    - Add policies for public access

  3. Relationships
    - Foreign key from debtData.category to debtOption.category_name

  4. Default Data
    - Insert default debt categories (BOH HING, TONG GAS, ROKOK)
*/

-- Create debtData table first (without foreign key constraint)
CREATE TABLE IF NOT EXISTS public."debtData" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_year text NOT NULL,
    worker_name text NOT NULL,
    category text NOT NULL,
    amount numeric(10,2) NOT NULL DEFAULT 0.00,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT debtdata_amount_check CHECK (amount >= 0)
);

-- Create debtOption table second
CREATE TABLE IF NOT EXISTS public."debtOption" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name text NOT NULL UNIQUE,
    description text,
    created_at timestamp with time zone DEFAULT now()
);

-- Add foreign key constraint after both tables exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_debt_category'
        AND table_name = 'debtData'
    ) THEN
        ALTER TABLE public."debtData" 
        ADD CONSTRAINT fk_debt_category 
        FOREIGN KEY (category) REFERENCES public."debtOption"(category_name) ON DELETE RESTRICT;
    END IF;
END $$;

-- Enable RLS on debtData
ALTER TABLE public."debtData" ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for debtData
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'debtData' 
        AND policyname = 'Enable all access for debtData'
    ) THEN
        CREATE POLICY "Enable all access for debtData" ON public."debtData"
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Enable RLS on debtOption
ALTER TABLE public."debtOption" ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for debtOption
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'debtOption' 
        AND policyname = 'Enable all access for debtOption'
    ) THEN
        CREATE POLICY "Enable all access for debtOption" ON public."debtOption"
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Create trigger function for updated_at on debtData
CREATE OR REPLACE FUNCTION public.update_debt_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at on debtData
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.triggers
        WHERE trigger_name = 'update_debtdata_updated_at'
        AND event_object_table = 'debtData'
    ) THEN
        CREATE TRIGGER update_debtdata_updated_at
        BEFORE UPDATE ON public."debtData"
        FOR EACH ROW
        EXECUTE FUNCTION public.update_debt_updated_at();
    END IF;
END $$;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_debt_data_worker_name ON public."debtData" (worker_name);
CREATE INDEX IF NOT EXISTS idx_debt_data_month_year ON public."debtData" (month_year);
CREATE INDEX IF NOT EXISTS idx_debt_data_category ON public."debtData" (category);
CREATE INDEX IF NOT EXISTS idx_debt_data_created_at ON public."debtData" (created_at);
CREATE INDEX IF NOT EXISTS idx_debt_option_category_name ON public."debtOption" (category_name);

-- Insert default debt categories into debtOption
INSERT INTO public."debtOption" (category_name, description)
VALUES
    ('BOH HING', 'Debt related to Boh Hing purchases'),
    ('TONG GAS', 'Debt related to Tong Gas purchases'),
    ('ROKOK', 'Debt related to cigarette purchases')
ON CONFLICT (category_name) DO NOTHING;