/*
  # Create phaseStartDateData table

  1. New Tables
    - `phaseStartDateData`
      - `id` (bigint, primary key, auto-generated)
      - `phase_id` (bigint, foreign key to PhaseData)
      - `start_date` (date, required)
      - `end_date` (date, required)
      - `created_at` (timestamp with timezone, default now())

  2. Security
    - Enable RLS on `phaseStartDateData` table
    - Add policy for public access to read/write data

  3. Constraints
    - Foreign key relationship with PhaseData table
    - Unique constraint on phase_id to ensure one start date per phase
*/

CREATE TABLE IF NOT EXISTS public."phaseStartDateData" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id bigint NOT NULL REFERENCES public."PhaseData"(id) ON DELETE CASCADE,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(phase_id)
);

ALTER TABLE public."phaseStartDateData" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for phaseStartDateData"
  ON public."phaseStartDateData"
  FOR ALL
  TO public
  USING (true)
  WITH CHECK (true);