/*
  # Create debt management tables

  1. New Tables
    - `debtData`
      - `id` (bigint, primary key)
      - `month_year` (text, not null)
      - `worker_name` (text, not null)
      - `category` (text, not null)
      - `amount` (numeric, not null, >= 0)
      - `created_at` (timestamp with time zone)
      - `updated_at` (timestamp with time zone)
    - `debtOption`
      - `id` (bigint, primary key)
      - `category_name` (text, unique, not null)
      - `description` (text)
      - `created_at` (timestamp with time zone)

  2. Security
    - Enable RLS on both tables
    - Add policies for public access

  3. Default Data
    - Insert default debt categories (BOH HING, TONG GAS, ROKOK)

  4. Triggers
    - Add updated_at trigger for debtData table
*/

-- Create debtData table first
CREATE TABLE IF NOT EXISTS public."debtData" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_year text NOT NULL,
    worker_name text NOT NULL,
    category text NOT NULL,
    amount numeric(10,2) NOT NULL DEFAULT 0.00,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Add constraints to debtData
ALTER TABLE public."debtData" 
ADD CONSTRAINT IF NOT EXISTS debtdata_amount_check CHECK (amount >= 0);

-- Create debtOption table second
CREATE TABLE IF NOT EXISTS public."debtOption" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now()
);

-- Add unique constraint to debtOption
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_name = 'debtOption' AND constraint_name = 'debtOption_category_name_key'
    ) THEN
        ALTER TABLE public."debtOption" ADD CONSTRAINT debtOption_category_name_key UNIQUE (category_name);
    END IF;
END $$;

-- Now add foreign key constraint to debtData
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_name = 'debtData' AND constraint_name = 'fk_debt_category'
    ) THEN
        ALTER TABLE public."debtData" 
        ADD CONSTRAINT fk_debt_category 
        FOREIGN KEY (category) REFERENCES public."debtOption"(category_name) ON DELETE RESTRICT;
    END IF;
END $$;

-- Enable RLS on debtData
ALTER TABLE public."debtData" ENABLE ROW LEVEL SECURITY;

-- Create policy for debtData
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'debtData' AND policyname = 'Enable all access for debtData'
    ) THEN
        CREATE POLICY "Enable all access for debtData" ON public."debtData"
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Enable RLS on debtOption
ALTER TABLE public."debtOption" ENABLE ROW LEVEL SECURITY;

-- Create policy for debtOption
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'debtOption' AND policyname = 'Enable all access for debtOption'
    ) THEN
        CREATE POLICY "Enable all access for debtOption" ON public."debtOption"
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Create trigger function for updated_at on debtData
CREATE OR REPLACE FUNCTION public.update_debt_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at on debtData
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.triggers 
        WHERE trigger_name = 'update_debtdata_updated_at'
    ) THEN
        CREATE TRIGGER update_debtdata_updated_at
        BEFORE UPDATE ON public."debtData"
        FOR EACH ROW
        EXECUTE FUNCTION public.update_debt_updated_at();
    END IF;
END $$;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_debt_data_worker_name ON public."debtData" (worker_name);
CREATE INDEX IF NOT EXISTS idx_debt_data_month_year ON public."debtData" (month_year);
CREATE INDEX IF NOT EXISTS idx_debt_data_category ON public."debtData" (category);
CREATE INDEX IF NOT EXISTS idx_debt_data_created_at ON public."debtData" (created_at);
CREATE INDEX IF NOT EXISTS idx_debt_option_category_name ON public."debtOption" (category_name);

-- Insert default debt categories into debtOption
INSERT INTO public."debtOption" (category_name, description)
VALUES
    ('BOH HING', 'Debt related to Boh Hing purchases'),
    ('TONG GAS', 'Debt related to Tong Gas purchases'),
    ('ROKOK', 'Debt related to cigarette purchases')
ON CONFLICT (category_name) DO NOTHING;